Update Jenkinsfile_io
Signed-off-by: SanthoshKumarHN <98937583+SanthoshKumarHN@users.noreply.github.com>

diff --git a/pipelines/Jenkinsfile_io b/pipelines/Jenkinsfile_io
--- a/pipelines/Jenkinsfile_io
+++ b/pipelines/Jenkinsfile_io
@@ -1,6 +1,8 @@
-pipeline {
+pipeline 
+{
     agent any 
-    environment {
+    environment 
+	{
 	// initialize the variables
 
 		repoPAth = "${gitOwner}/${repoName}"
@@ -13,39 +15,35 @@ pipeline {
 		HOME_DIR= "${WORKSPACE}/../"
 		workingDirectory = "${WORKSPACE}"
 		
- 		}
-    stages {
-	 stage('InitialiseRepo'){
-            steps {
+ 	}
+    stages 
+	{
+	 stage('InitialiseRepo')
+	 {
+            steps 
+			{
 		script{
-
 		echo "$WORKSPACE"
 		echo "${CUSTOMWORKSPACE}"
 		echo "Copy to the repo to custom workspace"
-		
 		sh '''
 		#cp -r "$WORKSPACE" "${CUSTOMWORKSPACE}"
 		#cd "${CUSTOMWORKSPACE}/${JOB_BASE_NAME}"
 		pwd
 		ls -ltr '''
 		script {
-
-
-		source_environment_hostname = sh ( returnStdout: true, script: '''yq -e ".tenant.hostname" configs/play.yml ''' )
-		source_environment_port = sh ( returnStdout: true, script: '''yq -e ".tenant.port" configs/play.yml ''' )
-		admin_user = sh ( returnStdout: true, script: '''yq -e ".tenant.admin_username" configs/play.yml ''' )
-		source_type = sh ( returnStdout: true, script: '''yq -e ".tenant.type" configs/play.yml ''' )
-		repo_user = sh ( returnStdout: true, script: '''yq -e ".repo.user" configs/repo.yml ''' )
-		}
-		
-			
+				source_environment_hostname = sh ( returnStdout: true, script: ''' yq -e ".tenant.hostname" configs/play.yml ''' )
+				source_environment_port = sh ( returnStdout: true, script: ''' yq -e ".tenant.port" configs/play.yml ''' )
+				admin_user = sh ( returnStdout: true, script: ''' yq -e ".tenant.admin_username" configs/play.yml ''' )
+				source_type = sh ( returnStdout: true, script: ''' yq -e ".tenant.type" configs/play.yml ''' )
+				repo_user = sh ( returnStdout: true, script: ''' yq -e ".repo.user" configs/repo.yml ''' )
+			}
 		echo "${source_environment_hostname}"
 		echo "${source_environment_port}"
         echo "${admin_user}"
 		echo "${source_type}"
 		echo "${repo_user}"
-	    
-	    
+	        
 	    echo "Verify the repo and create a repo"
 	    
 	    sh '''
@@ -56,74 +54,79 @@ pipeline {
 		
 		echo "Verified the repo and required branches"
             		}
+			}
 		}
-        }       
-	stage('Create and Sync Projects'){
-            steps {
+       
+	stage('Create and Sync Projects')
+	 {
+      steps {
 		script{
                 echo "Create / Sychronize the projects"
-				
-		sh  pwd
-  	LOCAL_DEV_URL = "https://${source_environment_hostname}:${source_environment_port}"
-      echo ${LOCAL_DEV_URL}
-	  echo ${init}
-      if ( ${init} == true ) {
-        echo "New repo created"
-        ''' pwd
-        ls -ltr
-        ######## Check & Create Project 
-        chmod +x ./pipelines/scripts/*.sh
-        ./pipelines/scripts/createProject.sh ${LOCAL_DEV_URL} ${admin_user} ${admin_password} ${repoName}
-		'''
-			}
-      else {
-    // Create a feature branch from prod 
-        echo "Repo Exists, Check and sync feature branch from Prod"
-        if ( ${synchProject} != true ) 
-        {
-          echo "Patch Initialize"
-          if ( ${assetID} == null) {
-            echo "##vso[task.logissue type=error;]Missing parameter \"assetID\""
-            echo "##vso[task.complete result=Failed;]"
-            sh 'exit 1'
-          }
-                  
-          if ( ${assetType}  == null){
-            echo "##vso[task.logissue type=error;]Missing parameter \"assetType\""
-            echo "##vso[task.complete result=Failed;]"
-            sh 'exit 1'
-          }
-          }
-          
-        else
-          echo "Project Initialize"
-        }
+				sh  pwd
+				LOCAL_DEV_URL = "https://${source_environment_hostname}:${source_environment_port}"
+				echo ${LOCAL_DEV_URL}
+				echo ${init}
+				if ( ${init} == true ) 
+				{
+					echo "New repo created"
+					''' pwd
+					ls -ltr
+					######## Check & Create Project 
+					chmod +x ./pipelines/scripts/*.sh
+					./pipelines/scripts/createProject.sh ${LOCAL_DEV_URL} ${admin_user} ${admin_password} ${repoName}
+					'''
+				}
+				else 
+				{
+				 // Create a feature branch from prod 
+				 echo "Repo Exists, Check and sync feature branch from Prod"
+			      if ( ${synchProject} != true ) 
+				  {
+					echo "Patch Initialize"
+					if ( ${assetID} == null) 
+					{
+						echo "##vso[task.logissue type=error;]Missing parameter \"assetID\""
+						echo "##vso[task.complete result=Failed;]"
+						sh 'exit 1'
+					}
+					 
+					if ( ${assetType}  == null)
+					{
+						echo "##vso[task.logissue type=error;]Missing parameter \"assetType\""
+						echo "##vso[task.complete result=Failed;]"
+						sh 'exit 1'
+					}
+				  }
+				  else
+					echo "Project Initialize"
+				}
 
-		
+					
           sh rm -rf ./${repoName}
 
-          git clone -b production "https://${repo_user}:${PAT}@github.com/${repo_user}/${repoName}.git"
-          sh cd $(repoName)
-          branchExists = $(git ls-remote --exit-code --heads origin ${featureBranchName})
-          if ( "${branchExists// }" ) 
-          {
-              echo "Branch ${featureBranchName} already exists"
-          }
-          else {
+      //    sh git clone -b production https://${repo_user}:${PAT}@github.com/${repo_user}/${repoName}.git
+      //    sh cd $(repoName)
+      //    branchExists = $(git ls-remote --exit-code --heads origin ${featureBranchName})
+      //    if ( "${branchExists// }" ) 
+      //    {
+      //        echo "Branch ${featureBranchName} already exists"
+      //    }
+      //    else {
               echo "Branch ${featureBranchName} doesnt exists, synching from prod ..."
-           ''' chmod +x ../${JOB_BASE_NAME}/pipelines/scripts/github/*.sh
-              ../${JOB_BASE_NAME}/pipelines/scripts/github/createFeatureFromProdBranch.sh ${devUser} ${featureBranchName} ${HOME_DIR} debug
-              # Project Check
-              chmod +x ../${JOB_BASE_NAME}/pipelines/scripts/*.sh
-              echo "Check and create Project ..."
-              ../${JOB_BASE_NAME}/pipelines/scripts/createProject.sh ${LOCAL_DEV_URL} ${admin_user} ${admin_password} ${repoName}
-              # Import
-                  echo "Importing asset ..."
-              ../${JOB_BASE_NAME}/pipelines/scripts/importAsset.sh ${LOCAL_DEV_URL} ${admin_user} ${admin_password} ${repoName} ${assetID} ${assetType} ${HOME_DIR} $(synchProject) $(source_type) debug
-          '''
-               }
+      //     ''' chmod +x ../${JOB_BASE_NAME}/pipelines/scripts/github/*.sh
+       //       ../${JOB_BASE_NAME}/pipelines/scripts/github/createFeatureFromProdBranch.sh ${devUser} ${featureBranchName} ${HOME_DIR} debug
+       //       # Project Check
+       //       chmod +x ../${JOB_BASE_NAME}/pipelines/scripts/*.sh
+       //       echo "Check and create Project ..."
+       //       ../${JOB_BASE_NAME}/pipelines/scripts/createProject.sh ${LOCAL_DEV_URL} ${admin_user} ${admin_password} ${repoName}
+       //       # Import
+       //           echo "Importing asset ..."
+       //       ../${JOB_BASE_NAME}/pipelines/scripts/importAsset.sh ${LOCAL_DEV_URL} ${admin_user} ${admin_password} ${repoName} ${assetID} ${assetType} ${HOME_DIR} $(synchProject) $(source_type) debug
+       //   '''
+       //        }
 				
             }
+		  }
         }
         stage('Deploy') {
             steps {
